name: cmcalc
description: "Qalculate frontend in Android and iOS"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.3
  google_fonts: ^6.2.1
  go_router: ^14.7.2
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.7.4
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Fira_Code/
    - assets/
