// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum ResultType: Int {
  case success = 0
  case warning = 1
  case failure = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct CalcResult {
  var resultType: ResultType
  var message: String
  var parsed: String
  var result: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CalcResult? {
    let resultType = pigeonVar_list[0] as! ResultType
    let message = pigeonVar_list[1] as! String
    let parsed = pigeonVar_list[2] as! String
    let result = pigeonVar_list[3] as! String

    return CalcResult(
      resultType: resultType,
      message: message,
      parsed: parsed,
      result: result
    )
  }
  func toList() -> [Any?] {
    return [
      resultType,
      message,
      parsed,
      result,
    ]
  }
}

private class CalculatorBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ResultType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CalcResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CalculatorBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ResultType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CalcResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CalculatorBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CalculatorBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CalculatorBridgePigeonCodecWriter(data: data)
  }
}

class CalculatorBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CalculatorBridgePigeonCodec(readerWriter: CalculatorBridgePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CalculatorWrapper {
  func calculate(command: String, completion: @escaping (Result<CalcResult, Error>) -> Void)
  func parseCommand(command: String, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CalculatorWrapperSetup {
  static var codec: FlutterStandardMessageCodec { CalculatorBridgePigeonCodec.shared }
  /// Sets up an instance of `CalculatorWrapper` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CalculatorWrapper?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let calculateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cmcalc.CalculatorWrapper.calculate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      calculateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let commandArg = args[0] as! String
        api.calculate(command: commandArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      calculateChannel.setMessageHandler(nil)
    }
    let parseCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.cmcalc.CalculatorWrapper.parseCommand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      parseCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let commandArg = args[0] as! String
        api.parseCommand(command: commandArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      parseCommandChannel.setMessageHandler(nil)
    }
  }
}
