// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, CalendarSystemFromDart) {
  CalendarSystemFromDartGregorian = 0,
  CalendarSystemFromDartMilankovic = 1,
  CalendarSystemFromDartJulian = 2,
  CalendarSystemFromDartIslamic = 3,
  CalendarSystemFromDartHebrew = 4,
  CalendarSystemFromDartEgyptian = 5,
  CalendarSystemFromDartPersian = 6,
  CalendarSystemFromDartCoptic = 7,
  CalendarSystemFromDartEthiopian = 8,
  CalendarSystemFromDartIndian = 9,
  CalendarSystemFromDartChinese = 10,
};

/// Wrapper for CalendarSystemFromDart to allow for nullability.
@interface CalendarSystemFromDartBox : NSObject <NSCopying>
@property(nonatomic, assign) CalendarSystemFromDart value;
- (instancetype)initWithValue:(CalendarSystemFromDart)value;
@end

@class CalendarExecuteState;

@interface CalendarExecuteState : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIsSuccess:(BOOL )isSuccess
    message:(nullable NSString *)message
    data:(NSDictionary<CalendarSystemFromDartBox *, NSArray<NSString *> *> *)data;
@property(nonatomic, assign) BOOL  isSuccess;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, copy) NSDictionary<CalendarSystemFromDartBox *, NSArray<NSString *> *> * data;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetCalendarBridgeCodec(void);

@protocol CalendarWrapper
- (void)setCalendarYearStem:(nullable NSNumber *)yearStem year:(NSInteger)year month:(NSInteger)month day:(NSInteger)day calendarSystem:(CalendarSystemFromDart)calendarSystem completion:(void (^)(CalendarExecuteState *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpCalendarWrapper(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CalendarWrapper> *_Nullable api);

extern void SetUpCalendarWrapperWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CalendarWrapper> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
