// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum CalendarSystemFromDart {
  gregorian,
  milankovic,
  julian,
  islamic,
  hebrew,
  egyptian,
  persian,
  coptic,
  ethiopian,
  indian,
  chinese,
}

class CalendarExecuteState {
  CalendarExecuteState({
    required this.isSuccess,
    this.message,
    required this.data,
  });

  bool isSuccess;

  String? message;

  Map<CalendarSystemFromDart, List<String>> data;

  Object encode() {
    return <Object?>[
      isSuccess,
      message,
      data,
    ];
  }

  static CalendarExecuteState decode(Object result) {
    result as List<Object?>;
    return CalendarExecuteState(
      isSuccess: result[0]! as bool,
      message: result[1] as String?,
      data: (result[2] as Map<Object?, Object?>?)!.cast<CalendarSystemFromDart, List<String>>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CalendarSystemFromDart) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CalendarExecuteState) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CalendarSystemFromDart.values[value];
      case 130: 
        return CalendarExecuteState.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CalendarWrapper {
  /// Constructor for [CalendarWrapper].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CalendarWrapper({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CalendarExecuteState> setCalendar(int? yearStem, int year, int month, int day, CalendarSystemFromDart calendarSystem) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.cmcalc.CalendarWrapper.setCalendar$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[yearStem, year, month, day, calendarSystem]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CalendarExecuteState?)!;
    }
  }
}
