// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

KalkResult calcStr({required String input}) =>
    RustLib.instance.api.crateApiKalkWrapperCalcStr(input: input);

class KalkResult {
  final bool isError;
  final String content;

  const KalkResult({
    required this.isError,
    required this.content,
  });

  @override
  int get hashCode => isError.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KalkResult &&
          runtimeType == other.runtimeType &&
          isError == other.isError &&
          content == other.content;
}
